# Generated by Django 5.0 on 2024-01-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_Model_Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_url', models.URLField(max_length=500)),
                ('home_html', models.TextField(max_length=1000000)),
                ('home_css', models.TextField(max_length=1000000)),
                ('home_js', models.TextField(max_length=1000000)),
            ],
        ),
    ]
